name: Deploy Vue Base Enterprise

on:
  push:
    branches:
      - master

jobs:
  create-directory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Access server and create a directory
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            mkdir -p /var/www/link-wholesaler/new-directory
          "
